//
// main.cpp
// Main file
// ----------------------------------
// Developed with embedXcode+
// https://embedXcode.weebly.com
//
// Project 		ProtoSystem
//
// Created by 	Hugo Chassaing, 12/02/2020 10:13
//              iMercy
//
// Copyright 	© Hugo Chassaing, 2020
// Licence 		All rights reserved
//
// See 			ProtoSystem.ino and ReadMe.txt for references
//
// ----------------------------------
// DO NOT EDIT THIS FILE.
// THE SKETCH IS IN ProtoSystem.ino
// ----------------------------------
//
// Last update: Jun 30, 2017 release 7.5.0

// IDE selection
#if defined(EMBEDXCODE)

// Core library and main()
// Minimal proxy main() to be updated at build
#include "Arduino.h"

int main(void)
{
    setup();

    for (;;)
    {
        loop();
    }

    return 0;
}

// Sketch
#include "ProtoSystem.ino"


#endif                                                                          // end embedXcode

